INCDIR = -I. -I.. -I$(SYSTEMC)/include  -I $(SCU_PATH)
LIBDIR = -L. -L.. -L$(SYSTEMC)/lib-linux
LIBS   = -lsystemc -lm
CFLAGS = -g -Wno-deprecated -Wall
OBJS   = $(SRCS:.C=.o)
EXE    = $(MODULE)
.SUFFIXES: .C .o

$(EXE): $(OBJS) 
	$(CC) $(CFLAGS) $(INCDIR) $(LIBDIR) -o $@ $(OBJS) $(LIBS) 2>&1 | c++filt

.C.o:
	$(CC) $(CFLAGS) $(INCDIR) -c $<

clean:
	rm -f $(OBJS) *~ $(EXE) core *.vcd

