#Nombre del programa
MODULE = Prueba

#compilador usado
CC= g++-4.4
#Archivos que se compilaran
SRCS =sc_main.cpp

#Direccion de systemc
#Nota:la del laboratorio es /home/usuarios/is/arqcomp/systemc/systemc-2.2.0
SYSTEMC = /usr/local/lib/systemc-2.2.0
SCU_PATH= /home/ronalanto03/Desktop/scu

include ./Makefile.defs

run:
	./$(EXE)

